[build]
  command = "pip install -r requirements.txt"
  publish = "src"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.11"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["src/**"]

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
