[build]
  command = "pip install -r requirements-netlify.txt"
  publish = "./src"
  functions = "./netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.10"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[functions]
  directory = "./netlify/functions"
  node_bundler = "esbuild"

[functions.api]
  included_files = ["./src/**"]
